#!/usr/bin/env bash
# Shared environment for the drone simulator tutorial.
# Sourced by every script in scripts/ — edit values here, not in the scripts.

# Where PX4-Autopilot gets cloned to (relative to project root).
export PX4_DIR="${PX4_DIR:-$(pwd)/PX4-Autopilot}"

# Which SITL simulation target to build/run.
#   Gazebo Classic (default, most tutorials use this): gazebo-classic_iris
#   Gazebo (Ignition) Harmonic, newer multirotor model: gz_x500
export PX4_SIM_TARGET="${PX4_SIM_TARGET:-gazebo-classic_iris}"

# PX4 release branch to build. "main" is bleeding edge; a tagged
# release is more stable for a tutorial.
export PX4_VERSION="${PX4_VERSION:-v1.15.0}"

# MAVLink endpoints PX4 SITL exposes by default.
export MAVLINK_UDP_PORT="${MAVLINK_UDP_PORT:-14540}"
export MAVLINK_GCS_PORT="${MAVLINK_GCS_PORT:-14550}"

# Fixed SITL takeoff/home position. PX4 reads these at startup and
# overrides the world's default spawn location. Pinning this to a
# known value (rather than whatever the world/model defaults to)
# means the QGroundControl demo mission in demo/obstacle_course_mission.plan
# — generated by scripts/make_qgc_plan.py from these exact values —
# lines up deterministically with worlds/obstacle_course.world's
# pylons and landing pad every time you run `make run-custom`. If you
# change these, re-run scripts/make_qgc_plan.py to regenerate the
# mission file to match.
export PX4_HOME_LAT="${PX4_HOME_LAT:-47.397742}"
export PX4_HOME_LON="${PX4_HOME_LON:-8.545594}"
export PX4_HOME_ALT="${PX4_HOME_ALT:-488.0}"

# Project-local Python virtual environment. Everything PX4/MAVSDK-side
# that needs Python (requirements.txt, jMAVSim/gz_bridge codegen at
# build time, takeoff_demo.py) runs inside this venv, NOT whatever
# python3 happens to be first on PATH. This matters for two reasons:
#   1. Ubuntu 24.04's system pip is "externally managed" (PEP 668) and
#      refuses `pip install --user` outright unless you pass
#      --break-system-packages. A venv sidesteps that restriction
#      cleanly instead of forcing system packages.
#   2. Conda/Anaconda environments (a "(base)" prompt, etc.) commonly
#      shadow python3/pip and can leak their own include/library paths
#      into native builds, which is a common source of confusing
#      version-mismatch errors in unrelated tools further down the
#      pipeline. A venv built from the SYSTEM python3 (see
#      scripts/setup_venv.sh) keeps this project's Python state fully
#      separate from any conda env you may have active.
export VENV_DIR="${VENV_DIR:-$(pwd)/.venv}"

# Call this after sourcing env.sh in any script that needs Python
# (pip installs, running takeoff_demo.py, or before invoking PX4's own
# build/setup scripts so THEY pick up this venv too). Safe no-op if
# the venv hasn't been created yet (scripts/setup_venv.sh does that).
activate_venv() {
  if [[ -f "${VENV_DIR}/bin/activate" ]]; then
    # shellcheck disable=SC1091
    source "${VENV_DIR}/bin/activate"
  fi
}

# Strip any conda/Anaconda path entries out of a single colon-separated
# environment variable, preserving every other entry and their order.
# Internal helper for sanitize_conda_build_env below.
_strip_conda_from_pathvar() {
  local var_name="$1" old_value="" part clean_value=""
  local IFS=':'
  if [[ -v "${var_name}" ]]; then
    old_value="${!var_name}"
  fi
  [[ -z "${old_value}" ]] && return 0
  for part in ${old_value}; do
    case "${part}" in
      *anaconda*|*miniconda*|*/conda/*|*Anaconda*|*Miniconda*) continue ;;
    esac
    if [[ -z "${clean_value}" ]]; then
      clean_value="${part}"
    else
      clean_value="${clean_value}:${part}"
    fi
  done
  export "${var_name}=${clean_value}"
}

# Call this before any cmake/ninja/make invocation that compiles C++
# (setup_px4.sh, run_sim.sh, run_custom_world.sh). Even after running
# `conda deactivate` in your interactive shell, conda/Anaconda
# installations (especially ones with the gcc_linux-64/gxx_linux-64
# "compiler" packages, or a base env that auto-activates on login)
# commonly leave CPATH/LIBRARY_PATH/PATH pointing into
# $HOME/anaconda3/{include,lib,bin} via activation hooks that don't
# always fully unwind. A single -isystem $HOME/anaconda3/include
# pulled in that way is enough to shadow apt's protobuf headers with
# conda's own copy, producing confusing "generated by a newer/older
# version of protoc" errors deep inside unrelated code (e.g. Gazebo's
# gz_bridge). Rather than depend on the interactive shell being clean,
# this strips conda entries from the *subshell these scripts run in*
# — it does not touch your actual interactive shell or .bashrc.
sanitize_conda_build_env() {
  local var
  local had_conda=0
  for var in PATH CPATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH LIBRARY_PATH \
             LD_LIBRARY_PATH PKG_CONFIG_PATH CMAKE_PREFIX_PATH; do
    if [[ -v "${var}" ]] && [[ "${!var}" == *conda* || "${!var}" == *Conda* ]]; then
      had_conda=1
    fi
    _strip_conda_from_pathvar "${var}"
  done
  if [[ "${had_conda}" == "1" ]]; then
    echo "==> Removed conda/Anaconda entries from PATH/CPATH/LIBRARY_PATH/etc. for this build"
  fi
}

# Correct PX4_SIM_TARGET if it's a Gazebo Classic target on a host
# where Classic literally cannot be built — OSRF doesn't publish
# gazebo11 packages for any Ubuntu release besides 20.04 (focal) and
# 22.04 (jammy), so CMake's configure step never defines a
# gazebo-classic_* ninja target there, and you get a confusing
# "ninja: error: unknown target 'gazebo-classic_iris'" instead of a
# clear explanation. This can happen even after install_deps.sh
# switches config/env.sh's DEFAULT to gz_x500 on unsupported releases:
# `export PX4_SIM_TARGET="${PX4_SIM_TARGET:-gz_x500}"` only supplies
# that default if the shell doesn't already have PX4_SIM_TARGET set —
# an already-exported value (e.g. left over from manually testing
# `PX4_SIM_TARGET=gazebo-classic_iris` in an earlier session) silently
# overrides it with no warning. Call this after sourcing env.sh in any
# script that builds/runs a general-purpose vehicle target
# (setup_px4.sh, run_sim.sh) — but NOT run_custom_world.sh, which
# deliberately requires a Classic target for its own world file and
# already gives a clear, specific error message for this exact
# mismatch (it needs you to actually be on a Classic-capable host).
resolve_sim_target() {
  local codename
  codename="$(lsb_release -cs 2>/dev/null || echo unknown)"
  case "${codename}" in
    focal|jammy) return 0 ;;  # Gazebo Classic is installable here — leave PX4_SIM_TARGET as-is
  esac
  case "${PX4_SIM_TARGET}" in
    gazebo-classic_*)
      echo "==> WARNING: PX4_SIM_TARGET='${PX4_SIM_TARGET}' but Gazebo Classic isn't"
      echo "    available on Ubuntu '${codename}' (OSRF doesn't publish gazebo11 for it),"
      echo "    so this target was never registered in the build and would fail with"
      echo "    'ninja: error: unknown target'. Overriding to PX4_SIM_TARGET=gz_x500 for"
      echo "    this run. To use Gazebo Classic (and worlds/obstacle_course.world /"
      echo "    'make run-custom'), run this project on Ubuntu 20.04 or 22.04 instead."
      export PX4_SIM_TARGET="gz_x500"
      ;;
  esac
}

# Uncomment if running headless / no GPU passthrough (e.g. some VMs, WSL).
# export LIBGL_ALWAYS_SOFTWARE=1
# export HEADLESS=1
