#!/usr/bin/env bash
# Clones PX4-Autopilot (if not already present) and runs its own
# ubuntu.sh dependency script + a first SITL build so later `make run`
# calls are fast.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../config/env.sh"

if [[ ! -f "${VENV_DIR}/bin/activate" ]]; then
  echo "Python venv not found at ${VENV_DIR}. Run 'make venv' first." >&2
  exit 1
fi
activate_venv
echo "==> Using venv Python: $(python --version 2>&1) at $(command -v python)"
sanitize_conda_build_env
resolve_sim_target

if [[ -d "${PX4_DIR}" ]]; then
  echo "==> PX4-Autopilot already present at ${PX4_DIR} — updating"
  git -C "${PX4_DIR}" fetch --tags
else
  echo "==> Cloning PX4-Autopilot (${PX4_VERSION}) into ${PX4_DIR}"
  git clone --branch "${PX4_VERSION}" --recursive \
    https://github.com/PX4/PX4-Autopilot.git "${PX4_DIR}"
fi

cd "${PX4_DIR}"
git checkout "${PX4_VERSION}"
git submodule update --init --recursive

echo "==> Patching known bad version specifiers in Tools/setup/requirements.txt"
# PX4's pinned requirements.txt (e.g. v1.15.0) contains lines like
# 'matplotlib>=3.0.*', which is invalid PEP 440 syntax — the '.*'
# wildcard is only legal with '==' or '!='. Old pip silently accepted
# it; modern pip (>=24) correctly rejects it and aborts the install.
# We rewrite any '>=X.Y.*' or '<=X.Y.*' to the equivalent bare
# '>=X.Y' / '<=X.Y' so pip can parse the file. This is a fix for a
# known upstream bug in the pinned file, not a change to which
# versions are actually required.
REQ_FILE="Tools/setup/requirements.txt"
if [[ -f "${REQ_FILE}" ]]; then
  sed -i -E 's/(>=|<=)([0-9]+(\.[0-9]+)*)\.\*/\1\2/g' "${REQ_FILE}"
fi

echo "==> Patching Java-version fallback in Tools/setup/ubuntu.sh (belt-and-suspenders)"
# ubuntu.sh sets a java_version variable per Ubuntu release (18.04->11,
# 20.04->13, 22.04->11); any other release falls through to
# java_version=14, and openjdk-14 was never an LTS release so it isn't
# packaged on modern Ubuntu. We patch this in case the sim-tools
# section below ends up running anyway.
UBUNTU_SETUP="Tools/setup/ubuntu.sh"
if [[ -f "${UBUNTU_SETUP}" ]] && grep -q 'java_version=14' "${UBUNTU_SETUP}"; then
  sudo apt-get update -qq || true
  JAVA_VER=""
  for v in 21 17 18 19 20 11 13; do
    if apt-cache show "openjdk-${v}-jdk" >/dev/null 2>&1; then
      JAVA_VER="${v}"
      break
    fi
  done
  if [[ -n "${JAVA_VER}" ]]; then
    sed -i "s/java_version=14/java_version=${JAVA_VER}/g" "${UBUNTU_SETUP}"
  fi
fi

# ubuntu.sh's own simulation-dependency section only explicitly
# handles Ubuntu 18.04/20.04/22.04 (Gazebo Classic) and 22.04
# (gz-garden for the "else" path is actually 18.04/20.04 — 22.04 gets
# gz-garden specifically). Every OTHER release, including 24.04,
# silently falls into the Gazebo-Classic install path and tries to
# apt-get gazebo11, which OSRF doesn't publish for noble. Rather than
# keep patching an aging upstream script line-by-line as Ubuntu moves
# on, we skip this section entirely on releases it doesn't explicitly
# support — scripts/install_deps.sh already installed the correct
# Gazebo (Harmonic) and Java version for this host at the OS level.
CODENAME="$(lsb_release -cs)"
SIM_FLAG=""
case "${CODENAME}" in
  focal|jammy) : ;;  # 20.04 / 22.04 — ubuntu.sh's sim-tools section works as-is
  *)
    echo "==> Ubuntu '${CODENAME}' isn't explicitly supported by PX4's ubuntu.sh sim-tools section."
    echo "    Skipping it (--no-sim-tools) since install_deps.sh already installed"
    echo "    the correct Gazebo/Java for this host."
    SIM_FLAG="--no-sim-tools"
    ;;
esac

echo "==> Running PX4's own Ubuntu simulation-dependency installer"
bash ./Tools/setup/ubuntu.sh --no-nuttx ${SIM_FLAG}

# If a previous run of this script (or a previous attempt with an
# earlier version of it) already partially configured/built this same
# PX4-Autopilot checkout, CMake's cached build directory can end up
# referencing an OLDER apt package state than what's installed now
# (e.g. Gazebo/protobuf got installed or upgraded AFTER the first
# configure). That mismatch surfaces as confusing C++ compile errors
# like "generated by a newer version of protoc" deep inside gz_bridge.
# Force a clean reconfigure so the build always matches the packages
# actually on disk right now.
if [[ -d build ]]; then
  echo "==> Clearing stale CMake/ninja build cache before (re)configuring"
  rm -rf build
fi

echo "==> First SITL build for target: ${PX4_SIM_TARGET}"
DONT_RUN=1 make px4_sitl "${PX4_SIM_TARGET}"

echo "==> PX4 SITL build complete. Next: 'make run' to launch the sim."
